import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

const myFont = localFont({
  src: "./font/Title_Light.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      {/* <body className={myFont.className}>{children}</body> 원본 */}
      <body className={myFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
