import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';
import { Providers } from './providers';
import NextAuthProviders from './components/NextAuthProviders';

const inter = Inter({ subsets: ['latin'] });

const myFont = localFont({
  src: './font/Pretendard-SemiBold.woff',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Next Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={myFont.className}>
      {/* <body className={inter.className}> */}
        <NextAuthProviders>
          <Providers>{children}</Providers>
        </NextAuthProviders>
      </body>
    </html>
  );
}
